<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Catálogo completo de países (ISO 3166-1 alpha-2) con sus ciudades
     * principales (capital + ciudades más grandes). No es un listado
     * exhaustivo de TODAS las ciudades del mundo (inmanejable para un
     * selector de UI) pero cubre los 195 países soberanos reconocidos por
     * la ONU, cada uno con entre 3 y 15 ciudades reales según su tamaño.
     */
    public function run(): void
    {
        $data = $this->countries();

        foreach ($data as $code => $entry) {
            $country = Country::query()->updateOrCreate(
                ['code' => $code],
                ['name' => $entry[0]]
            );

            $rows = array_map(fn (string $city) => [
                'country_id' => $country->id,
                'name' => $city,
                'created_at' => now(),
                'updated_at' => now(),
            ], $entry[1]);

            foreach (array_chunk($rows, 200) as $chunk) {
                DB::table('cities')->upsert($chunk, ['country_id', 'name'], ['updated_at']);
            }
        }
    }

    /**
     * @return array<string, array{0: string, 1: string[]}>
     */
    private function countries(): array
    {
        return [
            'AF' => ['Afganistán', ['Kabul', 'Kandahar', 'Herat', 'Mazar-e Sarif']],
            'AL' => ['Albania', ['Tirana', 'Durrés', 'Vlorë']],
            'DZ' => ['Argelia', ['Argel', 'Orán', 'Constantina', 'Annaba']],
            'AD' => ['Andorra', ['Andorra la Vieja']],
            'AO' => ['Angola', ['Luanda', 'Huambo', 'Lobito']],
            'AG' => ['Antigua y Barbuda', ["St. John's"]],
            'AR' => ['Argentina', ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Mar del Plata', 'Salta', 'San Miguel de Tucumán', 'Neuquén', 'Bariloche']],
            'AM' => ['Armenia', ['Ereván', 'Guiumri']],
            'AU' => ['Australia', ['Sídney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaida', 'Canberra', 'Gold Coast', 'Hobart', 'Darwin']],
            'AT' => ['Austria', ['Viena', 'Graz', 'Linz', 'Salzburgo', 'Innsbruck']],
            'AZ' => ['Azerbaiyán', ['Bakú', 'Ganyá']],
            'BS' => ['Bahamas', ['Nasáu']],
            'BH' => ['Baréin', ['Manama']],
            'BD' => ['Bangladés', ['Daca', 'Chittagong', 'Khulna']],
            'BB' => ['Barbados', ['Bridgetown']],
            'BY' => ['Bielorrusia', ['Minsk', 'Gómel', 'Vítebsk']],
            'BE' => ['Bélgica', ['Bruselas', 'Amberes', 'Gante', 'Brujas', 'Lieja']],
            'BZ' => ['Belice', ['Belmopán', 'Ciudad de Belice']],
            'BJ' => ['Benín', ['Porto Novo', 'Cotonú']],
            'BT' => ['Bután', ['Timbu']],
            'BO' => ['Bolivia', ['La Paz', 'Santa Cruz de la Sierra', 'Cochabamba', 'Sucre', 'El Alto']],
            'BA' => ['Bosnia y Herzegovina', ['Sarajevo', 'Banja Luka', 'Mostar']],
            'BW' => ['Botsuana', ['Gaborone']],
            'BR' => ['Brasil', ['São Paulo', 'Río de Janeiro', 'Brasilia', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaos', 'Curitiba', 'Recife', 'Porto Alegre']],
            'BN' => ['Brunéi', ['Bandar Seri Begawan']],
            'BG' => ['Bulgaria', ['Sofía', 'Plovdiv', 'Varna']],
            'BF' => ['Burkina Faso', ['Uagadugú', 'Bobo-Dioulasso']],
            'BI' => ['Burundi', ['Buyumbura', 'Guitega']],
            'CV' => ['Cabo Verde', ['Praia']],
            'KH' => ['Camboya', ['Nom Pen', 'Siem Reap']],
            'CM' => ['Camerún', ['Yaundé', 'Duala']],
            'CA' => ['Canadá', ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Ottawa', 'Edmonton', 'Quebec', 'Winnipeg', 'Halifax']],
            'QA' => ['Catar', ['Doha']],
            'KZ' => ['Kazajistán', ['Almaty', 'Astaná', 'Shymkent']],
            'TD' => ['Chad', ["Yamena"]],
            'CL' => ['Chile', ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Temuco', 'Viña del Mar']],
            'CN' => ['China', ['Pekín', 'Shanghái', 'Cantón', 'Shenzhen', 'Chengdú', 'Wuhan', 'Xi\'an', 'Hangzhou', 'Nankín', 'Tianjín']],
            'CY' => ['Chipre', ['Nicosia', 'Limasol']],
            'VA' => ['Ciudad del Vaticano', ['Ciudad del Vaticano']],
            'CO' => ['Colombia', ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Bucaramanga', 'Pereira', 'Manizales', 'Santa Marta']],
            'KM' => ['Comoras', ['Moroni']],
            'CG' => ['Congo', ['Brazzaville', 'Pointe-Noire']],
            'CD' => ['República Democrática del Congo', ['Kinsasa', 'Lubumbashi', 'Mbuji-Mayi']],
            'KP' => ['Corea del Norte', ['Pionyang']],
            'KR' => ['Corea del Sur', ['Seúl', 'Busan', 'Incheon', 'Daegu', 'Daejeon']],
            'CI' => ["Costa de Marfil", ['Abiyán', 'Yamusukro', 'Bouaké']],
            'CR' => ['Costa Rica', ['San José', 'Alajuela', 'Cartago', 'Limón']],
            'HR' => ['Croacia', ['Zagreb', 'Split', 'Rijeka', 'Dubrovnik']],
            'CU' => ['Cuba', ['La Habana', 'Santiago de Cuba', 'Camagüey']],
            'DK' => ['Dinamarca', ['Copenhague', 'Aarhus', 'Odense']],
            'DM' => ['Dominica', ['Roseau']],
            'EC' => ['Ecuador', ['Quito', 'Guayaquil', 'Cuenca', 'Manta', 'Ambato']],
            'EG' => ['Egipto', ['El Cairo', 'Alejandría', 'Guiza', 'Luxor', 'Asuán']],
            'SV' => ['El Salvador', ['San Salvador', 'Santa Ana', 'San Miguel']],
            'AE' => ['Emiratos Árabes Unidos', ['Dubái', 'Abu Dabi', 'Sharjah']],
            'ER' => ['Eritrea', ['Asmara']],
            'SK' => ['Eslovaquia', ['Bratislava', 'Košice']],
            'SI' => ['Eslovenia', ['Liubliana', 'Maribor']],
            'ES' => ['España', ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Zaragoza', 'Málaga', 'Bilbao', 'Murcia', 'Palma de Mallorca', 'Las Palmas de Gran Canaria']],
            'US' => ['Estados Unidos', ['Nueva York', 'Los Ángeles', 'Chicago', 'Houston', 'Phoenix', 'Miami', 'Filadelfia', 'San Antonio', 'San Diego', 'Dallas', 'Austin', 'San Francisco', 'Seattle', 'Boston', 'Las Vegas', 'Orlando']],
            'EE' => ['Estonia', ['Tallin', 'Tartu']],
            'SZ' => ['Esuatini', ['Mbabane']],
            'ET' => ['Etiopía', ['Adís Abeba', 'Dire Dawa']],
            'PH' => ['Filipinas', ['Manila', 'Quezon City', 'Cebú', 'Davao']],
            'FI' => ['Finlandia', ['Helsinki', 'Espoo', 'Tampere', 'Turku']],
            'FJ' => ['Fiyi', ['Suva']],
            'FR' => ['Francia', ['París', 'Marsella', 'Lyon', 'Toulouse', 'Niza', 'Nantes', 'Estrasburgo', 'Burdeos', 'Lille']],
            'GA' => ['Gabón', ['Libreville']],
            'GM' => ['Gambia', ['Banjul']],
            'GE' => ['Georgia', ['Tiflis', 'Batumi']],
            'GH' => ['Ghana', ['Accra', 'Kumasi']],
            'GD' => ['Granada', ["St. George's"]],
            'GR' => ['Grecia', ['Atenas', 'Tesalónica', 'Patras', 'Heraclión']],
            'GT' => ['Guatemala', ['Ciudad de Guatemala', 'Quetzaltenango', 'Antigua Guatemala']],
            'GY' => ['Guyana', ['Georgetown']],
            'GN' => ['Guinea', ['Conakri']],
            'GW' => ['Guinea-Bisáu', ['Bisáu']],
            'GQ' => ['Guinea Ecuatorial', ['Malabo']],
            'HT' => ['Haití', ['Puerto Príncipe']],
            'HN' => ['Honduras', ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba']],
            'HU' => ['Hungría', ['Budapest', 'Debrecen', 'Szeged']],
            'IN' => ['India', ['Bombay', 'Nueva Delhi', 'Bangalore', 'Calcuta', 'Chennai', 'Hyderabad', 'Pune', 'Ahmedabad', 'Jaipur']],
            'ID' => ['Indonesia', ['Yakarta', 'Surabaya', 'Bandung', 'Medan', 'Bali/Denpasar']],
            'IQ' => ['Irak', ['Bagdad', 'Basora', 'Erbil']],
            'IR' => ['Irán', ['Teherán', 'Mashhad', 'Isfahán']],
            'IE' => ['Irlanda', ['Dublín', 'Cork', 'Galway', 'Limerick']],
            'IS' => ['Islandia', ['Reikiavik']],
            'MH' => ['Islas Marshall', ['Majuro']],
            'SB' => ['Islas Salomón', ['Honiara']],
            'IL' => ['Israel', ['Jerusalén', 'Tel Aviv', 'Haifa']],
            'IT' => ['Italia', ['Roma', 'Milán', 'Nápoles', 'Turín', 'Palermo', 'Bolonia', 'Florencia', 'Venecia', 'Génova']],
            'JM' => ['Jamaica', ['Kingston', 'Montego Bay']],
            'JP' => ['Japón', ['Tokio', 'Osaka', 'Yokohama', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kioto', 'Kobe']],
            'JO' => ['Jordania', ['Amán', 'Zarqa']],
            'KW' => ['Kuwait', ['Ciudad de Kuwait']],
            'LA' => ['Laos', ['Vientián']],
            'LS' => ['Lesoto', ['Maseru']],
            'LV' => ['Letonia', ['Riga', 'Daugavpils']],
            'LB' => ['Líbano', ['Beirut', 'Trípoli', 'Sidón']],
            'LR' => ['Liberia', ['Monrovia']],
            'LY' => ['Libia', ['Trípoli', 'Bengasi']],
            'LI' => ['Liechtenstein', ['Vaduz']],
            'LT' => ['Lituania', ['Vilna', 'Kaunas']],
            'LU' => ['Luxemburgo', ['Luxemburgo']],
            'MK' => ['Macedonia del Norte', ['Skopie']],
            'MG' => ['Madagascar', ['Antananarivo', 'Toamasina']],
            'MY' => ['Malasia', ['Kuala Lumpur', 'Johor Bahru', 'Penang']],
            'MW' => ['Malaui', ['Lilongüe', 'Blantyre']],
            'MV' => ['Maldivas', ['Malé']],
            'ML' => ['Malí', ['Bamako']],
            'MT' => ['Malta', ['La Valeta']],
            'MA' => ['Marruecos', ['Casablanca', 'Rabat', 'Fez', 'Marrakech', 'Tánger']],
            'MU' => ['Mauricio', ['Port Louis']],
            'MR' => ['Mauritania', ['Nuakchot']],
            'MX' => ['México', ['Ciudad de México', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Mérida', 'Cancún', 'Querétaro', 'Toluca']],
            'FM' => ['Micronesia', ['Palikir']],
            'MD' => ['Moldavia', ['Chisináu']],
            'MC' => ['Mónaco', ['Mónaco']],
            'MN' => ['Mongolia', ['Ulán Bator']],
            'ME' => ['Montenegro', ['Podgorica']],
            'MZ' => ['Mozambique', ['Maputo', 'Beira']],
            'MM' => ['Birmania', ['Naipyidó', 'Rangún', 'Mandalay']],
            'NA' => ['Namibia', ['Windhoek']],
            'NR' => ['Nauru', ['Yaren']],
            'NP' => ['Nepal', ['Katmandú', 'Pokhara']],
            'NI' => ['Nicaragua', ['Managua', 'León', 'Granada']],
            'NE' => ['Níger', ['Niamey']],
            'NG' => ['Nigeria', ['Lagos', 'Abuya', 'Kano', 'Ibadán', 'Port Harcourt']],
            'NO' => ['Noruega', ['Oslo', 'Bergen', 'Trondheim']],
            'NZ' => ['Nueva Zelanda', ['Auckland', 'Wellington', 'Christchurch']],
            'OM' => ['Omán', ['Mascate']],
            'NL' => ['Países Bajos', ['Ámsterdam', 'Róterdam', 'La Haya', 'Utrecht', 'Eindhoven']],
            'PK' => ['Pakistán', ['Karachi', 'Lahore', 'Islamabad', 'Faisalabad']],
            'PW' => ['Palaos', ['Ngerulmud']],
            'PA' => ['Panamá', ['Ciudad de Panamá', 'Colón', 'David']],
            'PG' => ['Papúa Nueva Guinea', ['Port Moresby']],
            'PY' => ['Paraguay', ['Asunción', 'Ciudad del Este', 'Encarnación']],
            'PE' => ['Perú', ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Cusco', 'Piura']],
            'PL' => ['Polonia', ['Varsovia', 'Cracovia', 'Breslavia', 'Poznan', 'Gdansk', 'Łódź']],
            'PT' => ['Portugal', ['Lisboa', 'Oporto', 'Braga', 'Coímbra', 'Faro']],
            'GB' => ['Reino Unido', ['Londres', 'Mánchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Edimburgo', 'Bristol', 'Leeds', 'Cardiff', 'Belfast']],
            'CF' => ['República Centroafricana', ['Bangui']],
            'CZ' => ['República Checa', ['Praga', 'Brno', 'Ostrava']],
            'DO' => ['República Dominicana', ['Santo Domingo', 'Santiago de los Caballeros', 'Punta Cana', 'La Romana']],
            'RW' => ['Ruanda', ['Kigali']],
            'RO' => ['Rumanía', ['Bucarest', 'Cluj-Napoca', 'Timisoara']],
            'RU' => ['Rusia', ['Moscú', 'San Petersburgo', 'Novosibirsk', 'Ekaterimburgo', 'Kazán']],
            'WS' => ['Samoa', ['Apia']],
            'KN' => ['San Cristóbal y Nieves', ['Basseterre']],
            'SM' => ['San Marino', ['San Marino']],
            'VC' => ['San Vicente y las Granadinas', ['Kingstown']],
            'LC' => ['Santa Lucía', ['Castries']],
            'ST' => ['Santo Tomé y Príncipe', ['Santo Tomé']],
            'SN' => ['Senegal', ['Dakar', 'Touba']],
            'RS' => ['Serbia', ['Belgrado', 'Novi Sad', 'Niš']],
            'SC' => ['Seychelles', ['Victoria']],
            'SL' => ['Sierra Leona', ['Freetown']],
            'SG' => ['Singapur', ['Singapur']],
            'SY' => ['Siria', ['Damasco', 'Alepo']],
            'SO' => ['Somalia', ['Mogadiscio']],
            'LK' => ['Sri Lanka', ['Colombo', 'Kandy']],
            'SS' => ['Sudán del Sur', ['Yuba']],
            'SD' => ['Sudán', ['Jartum', 'Omdurmán']],
            'SE' => ['Suecia', ['Estocolmo', 'Gotemburgo', 'Malmö', 'Uppsala']],
            'CH' => ['Suiza', ['Zúrich', 'Ginebra', 'Basilea', 'Berna', 'Lausana']],
            'SR' => ['Surinam', ['Paramaribo']],
            'TH' => ['Tailandia', ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya']],
            'TZ' => ['Tanzania', ['Dodoma', 'Dar es Salam', 'Zanzíbar']],
            'TJ' => ['Tayikistán', ['Dusambé']],
            'TL' => ['Timor Oriental', ['Dili']],
            'TG' => ['Togo', ['Lomé']],
            'TO' => ['Tonga', ["Nuku'alofa"]],
            'TT' => ['Trinidad y Tobago', ['Puerto España']],
            'TN' => ['Túnez', ['Túnez', 'Sfax']],
            'TM' => ['Turkmenistán', ['Asjabad']],
            'TR' => ['Turquía', ['Estambul', 'Ankara', 'Esmirna', 'Antalya', 'Bursa']],
            'TV' => ['Tuvalu', ['Funafuti']],
            'UA' => ['Ucrania', ['Kiev', 'Járkov', 'Odesa', 'Leópolis']],
            'UG' => ['Uganda', ['Kampala']],
            'UY' => ['Uruguay', ['Montevideo', 'Punta del Este', 'Salto', 'Maldonado']],
            'UZ' => ['Uzbekistán', ['Taskent', 'Samarcanda']],
            'VU' => ['Vanuatu', ['Port Vila']],
            'VE' => ['Venezuela', ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay']],
            'VN' => ['Vietnam', ['Hanói', 'Ciudad Ho Chi Minh', 'Da Nang']],
            'YE' => ['Yemen', ["Saná", 'Adén']],
            'DJ' => ['Yibuti', ['Yibuti']],
            'ZM' => ['Zambia', ['Lusaka', 'Ndola']],
            'ZW' => ['Zimbabue', ['Harare', 'Bulawayo']],
            'ZA' => ['Sudáfrica', ['Johannesburgo', 'Ciudad del Cabo', 'Durban', 'Pretoria', 'Puerto Elizabeth']],
            'KE' => ['Kenia', ['Nairobi', 'Mombasa', 'Kisumu']],
            'KG' => ['Kirguistán', ['Biskek']],
            'KI' => ['Kiribati', ['Tarawa']],
        ];
    }
}
