<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\MuscleGroup;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    /**
     * Biblioteca base de ejercicios. No pretende ser exhaustiva (el objetivo
     * de producto es 150-300, ver docs/02-modelo-datos-bd.md) — este set
     * cubre cada grupo muscular y cada tipo de equipo lo suficiente para que
     * el motor de rutinas genere planes reales y variados. Ampliar el
     * catálogo es trabajo de contenido, no de arquitectura.
     */
    public function run(): void
    {
        $muscles = MuscleGroup::query()->pluck('id', 'slug');

        $exercises = [
            // ---- Pecho ----
            ['name' => 'Press banca con barra', 'muscle' => 'chest', 'secondary' => ['triceps', 'shoulders'], 'equipment' => 'barbell', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'Baja la barra controlada hasta rozar el pecho y empuja hasta extender los brazos.',
                'common_mistakes' => 'Rebotar la barra en el pecho o despegar los glúteos del banco.',
                'tips' => 'Retrae los omóplatos y mantén los pies firmes en el suelo durante todo el movimiento.'],
            ['name' => 'Press banca con mancuernas', 'muscle' => 'chest', 'secondary' => ['triceps', 'shoulders'], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Empuja ambas mancuernas hacia arriba hasta casi juntarlas sobre el pecho.',
                'common_mistakes' => 'Dejar caer los codos demasiado bajo, forzando el hombro.',
                'tips' => 'Permite mayor rango de movimiento que la barra; controla el descenso.'],
            ['name' => 'Press inclinado con barra', 'muscle' => 'chest', 'secondary' => ['shoulders', 'triceps'], 'equipment' => 'barbell', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'Con el banco a 30-45°, baja la barra a la parte superior del pecho y empuja.',
                'common_mistakes' => 'Inclinar demasiado el banco, convirtiéndolo en un press de hombro.',
                'tips' => 'Prioriza pecho superior; útil para desarrollo completo del pectoral.'],
            ['name' => 'Press inclinado con mancuernas', 'muscle' => 'chest', 'secondary' => ['shoulders', 'triceps'], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Empuja las mancuernas hacia arriba y ligeramente hacia adentro.',
                'common_mistakes' => 'Arquear excesivamente la espalda baja.',
                'tips' => 'Buena alternativa cuando no hay barra disponible.'],
            ['name' => 'Aperturas con mancuernas', 'muscle' => 'chest', 'secondary' => [], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Con los codos ligeramente flexionados, abre los brazos en arco y vuelve a juntarlos sobre el pecho.',
                'common_mistakes' => 'Extender completamente los codos, forzando la articulación.',
                'tips' => 'Piensa en "abrazar un árbol" para mantener la tensión en el pecho.'],
            ['name' => 'Cruce de poleas', 'muscle' => 'chest', 'secondary' => [], 'equipment' => 'cables', 'level' => 'intermediate', 'type' => 'isolation',
                'instructions' => 'Junta las poleas frente al cuerpo en un movimiento de arco, contrayendo el pecho.',
                'common_mistakes' => 'Usar demasiado peso y perder el rango de movimiento.',
                'tips' => 'Excelente para el final de la sesión, mantiene tensión constante.'],
            ['name' => 'Fondos en paralelas', 'muscle' => 'chest', 'secondary' => ['triceps', 'shoulders'], 'equipment' => 'bodyweight_only', 'level' => 'advanced', 'type' => 'compound',
                'instructions' => 'Baja el cuerpo flexionando los codos e inclinando el torso hacia adelante, luego empuja.',
                'common_mistakes' => 'Bajar demasiado y sobrecargar el hombro anterior.',
                'tips' => 'Inclinar el torso enfatiza más el pecho que el tríceps.'],
            ['name' => 'Press de pecho en máquina', 'muscle' => 'chest', 'secondary' => ['triceps'], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Empuja las manijas hacia adelante hasta extender los brazos sin bloquear los codos.',
                'common_mistakes' => 'Ajustar mal la altura del asiento.',
                'tips' => 'Buena opción para principiantes por su estabilidad.'],
            ['name' => 'Flexiones de pecho', 'muscle' => 'chest', 'secondary' => ['triceps', 'core'], 'equipment' => 'bodyweight_only', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Baja el cuerpo en línea recta hasta casi tocar el suelo y empuja de vuelta.',
                'common_mistakes' => 'Dejar caer la cadera o elevar demasiado los glúteos.',
                'tips' => 'Ajusta la dificultad apoyando las rodillas si es necesario.'],
            ['name' => 'Press con banda de resistencia', 'muscle' => 'chest', 'secondary' => ['triceps'], 'equipment' => 'resistance_bands', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Ancla la banda detrás del cuerpo y empuja hacia adelante como en un press.',
                'common_mistakes' => 'Perder tensión en la banda al final del recorrido.',
                'tips' => 'Ideal para entrenar en casa sin equipo pesado.'],

            // ---- Espalda ----
            ['name' => 'Dominadas', 'muscle' => 'back', 'secondary' => ['biceps'], 'equipment' => 'pull_up_bar', 'level' => 'advanced', 'type' => 'compound',
                'instructions' => 'Cuelga de la barra y tira del cuerpo hacia arriba hasta que la barbilla supere la barra.',
                'common_mistakes' => 'Usar impulso (kipping) en lugar de fuerza controlada.',
                'tips' => 'Si aún no puedes hacer una completa, usa banda de asistencia.'],
            ['name' => 'Jalón al pecho', 'muscle' => 'back', 'secondary' => ['biceps'], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Tira de la barra hacia la parte superior del pecho, llevando los codos hacia abajo.',
                'common_mistakes' => 'Tirar con los brazos en vez de iniciar el jalón con la espalda.',
                'tips' => 'Buena alternativa a dominadas mientras se gana fuerza.'],
            ['name' => 'Remo con barra', 'muscle' => 'back', 'secondary' => ['biceps'], 'equipment' => 'barbell', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'Con el torso inclinado, tira de la barra hacia el abdomen apretando los omóplatos.',
                'common_mistakes' => 'Redondear la espalda baja bajo carga.',
                'tips' => 'Mantén el core firme durante todo el movimiento.'],
            ['name' => 'Remo con mancuerna a una mano', 'muscle' => 'back', 'secondary' => ['biceps'], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Apoya una rodilla y mano en el banco, tira de la mancuerna hacia la cadera.',
                'common_mistakes' => 'Rotar el torso para ayudar con impulso.',
                'tips' => 'Permite trabajar cada lado de forma independiente.'],
            ['name' => 'Remo en polea sentado', 'muscle' => 'back', 'secondary' => ['biceps'], 'equipment' => 'cables', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Tira del agarre hacia el abdomen manteniendo la espalda recta.',
                'common_mistakes' => 'Balancear el torso hacia adelante y atrás excesivamente.',
                'tips' => 'Pausa un segundo en la contracción máxima.'],
            ['name' => 'Peso muerto', 'muscle' => 'back', 'secondary' => ['hamstrings', 'glutes'], 'equipment' => 'barbell', 'level' => 'advanced', 'type' => 'compound',
                'instructions' => 'Con la barra cerca de las espinillas, levanta extendiendo cadera y rodillas a la vez.',
                'common_mistakes' => 'Redondear la espalda baja al levantar.',
                'tips' => 'Ejercicio técnico: prioriza la forma antes que el peso.'],
            ['name' => 'Peso muerto rumano con barra', 'muscle' => 'back', 'secondary' => ['hamstrings', 'glutes'], 'equipment' => 'barbell', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'Baja la barra pegada a las piernas manteniendo una ligera flexión de rodilla.',
                'common_mistakes' => 'Flexionar demasiado las rodillas, convirtiéndolo en sentadilla.',
                'tips' => 'Enfócate en la sensación de estiramiento en isquiotibiales.'],
            ['name' => 'Face pull', 'muscle' => 'back', 'secondary' => ['shoulders'], 'equipment' => 'cables', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Tira de la cuerda hacia la cara separando las manos al final del recorrido.',
                'common_mistakes' => 'Usar demasiado peso y perder la forma.',
                'tips' => 'Excelente para la salud del hombro y la postura.'],
            ['name' => 'Remo en T', 'muscle' => 'back', 'secondary' => ['biceps'], 'equipment' => 'barbell', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'Con el torso inclinado, tira de la barra hacia el pecho apretando la espalda.',
                'common_mistakes' => 'Extender completamente los brazos sin control en la bajada.',
                'tips' => 'Añade grosor a la espalda media.'],
            ['name' => 'Hiperextensiones', 'muscle' => 'back', 'secondary' => ['hamstrings', 'glutes'], 'equipment' => 'bodyweight_only', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Baja el torso controlado y sube extendiendo la espalda baja sin hiperextender.',
                'common_mistakes' => 'Subir demasiado arqueando en exceso la zona lumbar.',
                'tips' => 'Refuerza la cadena posterior y protege la espalda baja.'],
            ['name' => 'Remo con banda de resistencia', 'muscle' => 'back', 'secondary' => ['biceps'], 'equipment' => 'resistance_bands', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Ancla la banda al frente y tira hacia el abdomen apretando la espalda.',
                'common_mistakes' => 'Encorvar los hombros hacia adelante al final.',
                'tips' => 'Alternativa práctica al remo con máquina en casa.'],

            // ---- Hombros ----
            ['name' => 'Press militar con barra', 'muscle' => 'shoulders', 'secondary' => ['triceps'], 'equipment' => 'barbell', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'Empuja la barra desde los hombros hasta la extensión completa sobre la cabeza.',
                'common_mistakes' => 'Arquear excesivamente la espalda baja para compensar.',
                'tips' => 'Aprieta glúteos y abdomen para mantener el torso estable.'],
            ['name' => 'Press de hombro con mancuernas', 'muscle' => 'shoulders', 'secondary' => ['triceps'], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Empuja ambas mancuernas hacia arriba hasta casi juntarlas sobre la cabeza.',
                'common_mistakes' => 'Bajar las mancuernas demasiado rápido sin control.',
                'tips' => 'Permite un recorrido más natural que la barra.'],
            ['name' => 'Elevaciones laterales', 'muscle' => 'shoulders', 'secondary' => [], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Eleva los brazos hacia los lados hasta la altura de los hombros.',
                'common_mistakes' => 'Usar impulso balanceando el torso.',
                'tips' => 'Controla más la bajada que la subida para maximizar tensión.'],
            ['name' => 'Elevaciones frontales', 'muscle' => 'shoulders', 'secondary' => [], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Eleva una o ambas mancuernas al frente hasta la altura del hombro.',
                'common_mistakes' => 'Elevar por encima de la altura del hombro innecesariamente.',
                'tips' => 'Enfatiza el deltoide anterior.'],
            ['name' => 'Pájaros (deltoide posterior)', 'muscle' => 'shoulders', 'secondary' => ['back'], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Inclinado hacia adelante, abre los brazos hacia los lados apretando los omóplatos.',
                'common_mistakes' => 'Usar demasiado peso y perder el rango de movimiento.',
                'tips' => 'Clave para el desarrollo equilibrado del hombro.'],
            ['name' => 'Press Arnold', 'muscle' => 'shoulders', 'secondary' => ['triceps'], 'equipment' => 'dumbbells', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'Comienza con las palmas hacia ti y rota mientras empujas hacia arriba.',
                'common_mistakes' => 'Perder la rotación y convertirlo en un press normal.',
                'tips' => 'Trabaja las tres cabezas del deltoide en un solo movimiento.'],
            ['name' => 'Elevaciones laterales en polea', 'muscle' => 'shoulders', 'secondary' => [], 'equipment' => 'cables', 'level' => 'intermediate', 'type' => 'isolation',
                'instructions' => 'Con la polea baja, eleva el brazo hacia el lateral manteniendo tensión constante.',
                'common_mistakes' => 'Girar el torso para ayudar con impulso.',
                'tips' => 'La polea mantiene tensión incluso al inicio del movimiento, a diferencia de la mancuerna.'],
            ['name' => 'Press de hombro en máquina', 'muscle' => 'shoulders', 'secondary' => ['triceps'], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Empuja las manijas hacia arriba hasta casi extender los brazos.',
                'common_mistakes' => 'Ajustar mal la altura del asiento.',
                'tips' => 'Opción estable para principiantes o para llegar al fallo con seguridad.'],

            // ---- Bíceps ----
            ['name' => 'Curl de bíceps con barra', 'muscle' => 'biceps', 'secondary' => [], 'equipment' => 'barbell', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Flexiona los codos llevando la barra hacia los hombros sin mover el torso.',
                'common_mistakes' => 'Balancear el cuerpo para generar impulso.',
                'tips' => 'Mantén los codos pegados al torso durante todo el recorrido.'],
            ['name' => 'Curl de bíceps con mancuernas', 'muscle' => 'biceps', 'secondary' => [], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Flexiona alternando o ambos brazos a la vez, girando la muñeca al subir.',
                'common_mistakes' => 'Subir demasiado rápido perdiendo tensión.',
                'tips' => 'La supinación (girar la palma) enfatiza más el bíceps.'],
            ['name' => 'Curl martillo', 'muscle' => 'biceps', 'secondary' => [], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Flexiona con agarre neutro (palmas enfrentadas) hacia los hombros.',
                'common_mistakes' => 'Rotar la muñeca durante el movimiento.',
                'tips' => 'También trabaja el antebrazo y el braquial.'],
            ['name' => 'Curl en banco Scott', 'muscle' => 'biceps', 'secondary' => [], 'equipment' => 'barbell', 'level' => 'intermediate', 'type' => 'isolation',
                'instructions' => 'Con el brazo apoyado en el banco, flexiona sin despegar el tríceps del soporte.',
                'common_mistakes' => 'Extender completamente el codo bajo carga, forzando la articulación.',
                'tips' => 'Aísla muy bien el bíceps al eliminar el impulso del cuerpo.'],
            ['name' => 'Curl en polea', 'muscle' => 'biceps', 'secondary' => [], 'equipment' => 'cables', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Flexiona los codos tirando de la barra o cuerda hacia los hombros.',
                'common_mistakes' => 'Dejar que los codos se muevan hacia adelante.',
                'tips' => 'Mantiene tensión constante en todo el rango.'],
            ['name' => 'Curl con banda de resistencia', 'muscle' => 'biceps', 'secondary' => [], 'equipment' => 'resistance_bands', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Pisa la banda y flexiona los codos hacia los hombros.',
                'common_mistakes' => 'Perder tensión en la banda al inicio del movimiento.',
                'tips' => 'Buena opción de bíceps sin necesidad de pesas.'],

            // ---- Tríceps ----
            ['name' => 'Press francés', 'muscle' => 'triceps', 'secondary' => [], 'equipment' => 'barbell', 'level' => 'intermediate', 'type' => 'isolation',
                'instructions' => 'Acostado, baja la barra hacia la frente flexionando solo los codos.',
                'common_mistakes' => 'Mover los codos hacia afuera durante el descenso.',
                'tips' => 'Controla bien el peso; es una posición vulnerable si se pierde el control.'],
            ['name' => 'Extensión de tríceps en polea', 'muscle' => 'triceps', 'secondary' => [], 'equipment' => 'cables', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Con los codos fijos al torso, extiende los brazos empujando la barra hacia abajo.',
                'common_mistakes' => 'Separar los codos del cuerpo durante el movimiento.',
                'tips' => 'Uno de los ejercicios de aislamiento más eficientes para tríceps.'],
            ['name' => 'Fondos de tríceps en banco', 'muscle' => 'triceps', 'secondary' => ['chest'], 'equipment' => 'bodyweight_only', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Con manos en el banco detrás de ti, flexiona y extiende los codos.',
                'common_mistakes' => 'Bajar demasiado forzando el hombro.',
                'tips' => 'Ajusta la dificultad flexionando más o menos las rodillas.'],
            ['name' => 'Press cerrado', 'muscle' => 'triceps', 'secondary' => ['chest'], 'equipment' => 'barbell', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'Press de banca con agarre estrecho, codos cerca del torso.',
                'common_mistakes' => 'Agarre demasiado estrecho que fuerza la muñeca.',
                'tips' => 'Buen ejercicio compuesto para tríceps con carga pesada.'],
            ['name' => 'Extensión de tríceps con mancuerna', 'muscle' => 'triceps', 'secondary' => [], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Sobre la cabeza, baja la mancuerna detrás de la nuca y extiende.',
                'common_mistakes' => 'Abrir demasiado los codos hacia los lados.',
                'tips' => 'Se puede hacer a una o dos manos.'],
            ['name' => 'Patada de tríceps', 'muscle' => 'triceps', 'secondary' => [], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Con el torso inclinado, extiende el codo hacia atrás manteniéndolo fijo.',
                'common_mistakes' => 'Mover el hombro en vez de solo el codo.',
                'tips' => 'Enfócate en la contracción máxima al final del movimiento.'],

            // ---- Cuádriceps ----
            ['name' => 'Sentadilla con barra', 'muscle' => 'quads', 'secondary' => ['glutes', 'hamstrings'], 'equipment' => 'squat_rack', 'level' => 'advanced', 'type' => 'compound',
                'instructions' => 'Baja la cadera hacia atrás y abajo hasta al menos 90°, luego empuja el suelo para subir.',
                'common_mistakes' => 'Dejar que las rodillas colapsen hacia adentro.',
                'tips' => 'El ejercicio más completo para tren inferior; prioriza técnica sobre carga.'],
            ['name' => 'Sentadilla goblet', 'muscle' => 'quads', 'secondary' => ['glutes'], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Sostén una mancuerna contra el pecho y realiza una sentadilla completa.',
                'common_mistakes' => 'Inclinar demasiado el torso hacia adelante.',
                'tips' => 'Excelente para aprender el patrón de sentadilla.'],
            ['name' => 'Prensa de piernas', 'muscle' => 'quads', 'secondary' => ['glutes'], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Empuja la plataforma extendiendo las piernas sin bloquear las rodillas.',
                'common_mistakes' => 'Bajar demasiado despegando la zona lumbar del respaldo.',
                'tips' => 'Permite cargar volumen alto con menor demanda técnica.'],
            ['name' => 'Extensión de cuádriceps', 'muscle' => 'quads', 'secondary' => [], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Extiende las piernas contra la almohadilla hasta casi bloquear la rodilla.',
                'common_mistakes' => 'Usar impulso en lugar de control.',
                'tips' => 'Ideal para aislar el cuádriceps al final de la sesión de piernas.'],
            ['name' => 'Zancadas', 'muscle' => 'quads', 'secondary' => ['glutes'], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Da un paso adelante y baja hasta que ambas rodillas formen 90°.',
                'common_mistakes' => 'Dar un paso demasiado corto, forzando la rodilla delantera.',
                'tips' => 'Alterna piernas o completa una serie por lado.'],
            ['name' => 'Sentadilla búlgara', 'muscle' => 'quads', 'secondary' => ['glutes'], 'equipment' => 'dumbbells', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'Con el pie trasero elevado en un banco, baja la cadera en la pierna delantera.',
                'common_mistakes' => 'Apoyar demasiado peso en el pie trasero.',
                'tips' => 'Muy efectiva para fuerza unilateral y estabilidad.'],
            ['name' => 'Sentadilla frontal', 'muscle' => 'quads', 'secondary' => ['core'], 'equipment' => 'barbell', 'level' => 'advanced', 'type' => 'compound',
                'instructions' => 'Con la barra al frente sobre los hombros, baja manteniendo el torso erguido.',
                'common_mistakes' => 'Dejar caer los codos, perdiendo la posición de la barra.',
                'tips' => 'Exige más movilidad de tobillo y muñeca que la sentadilla trasera.'],
            ['name' => 'Sentadilla con kettlebell', 'muscle' => 'quads', 'secondary' => ['glutes'], 'equipment' => 'kettlebells', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Sostén la kettlebell contra el pecho y realiza una sentadilla completa.',
                'common_mistakes' => 'Levantar los talones del suelo.',
                'tips' => 'Alternativa a la sentadilla goblet cuando solo hay kettlebells.'],

            // ---- Isquiotibiales ----
            ['name' => 'Peso muerto rumano con mancuernas', 'muscle' => 'hamstrings', 'secondary' => ['glutes', 'back'], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Baja las mancuernas pegadas a las piernas con una ligera flexión de rodilla.',
                'common_mistakes' => 'Redondear la espalda al bajar.',
                'tips' => 'Siente el estiramiento en isquiotibiales antes de subir.'],
            ['name' => 'Curl femoral', 'muscle' => 'hamstrings', 'secondary' => [], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Flexiona las rodillas llevando el talón hacia los glúteos.',
                'common_mistakes' => 'Levantar la cadera del respaldo.',
                'tips' => 'Aislamiento directo y seguro para isquiotibiales.'],
            ['name' => 'Buenos días', 'muscle' => 'hamstrings', 'secondary' => ['back', 'glutes'], 'equipment' => 'barbell', 'level' => 'advanced', 'type' => 'compound',
                'instructions' => 'Con la barra en la espalda, inclina el torso hacia adelante manteniendo la espalda recta.',
                'common_mistakes' => 'Usar demasiado peso antes de dominar la técnica.',
                'tips' => 'Empieza con cargas ligeras; exige buena técnica.'],
            ['name' => 'Peso muerto a una pierna', 'muscle' => 'hamstrings', 'secondary' => ['glutes', 'core'], 'equipment' => 'dumbbells', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'En apoyo sobre una pierna, baja la mancuerna mientras la pierna libre se eleva atrás.',
                'common_mistakes' => 'Rotar la cadera en lugar de mantenerla cuadrada.',
                'tips' => 'Excelente para equilibrio, estabilidad y fuerza unilateral.'],

            // ---- Glúteos ----
            ['name' => 'Hip thrust', 'muscle' => 'glutes', 'secondary' => ['hamstrings'], 'equipment' => 'barbell', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'Con la espalda apoyada en el banco, empuja la cadera hacia arriba con la barra sobre las caderas.',
                'common_mistakes' => 'Hiperextender la espalda baja en lugar de usar los glúteos.',
                'tips' => 'Uno de los ejercicios más efectivos para glúteo mayor.'],
            ['name' => 'Puente de glúteos', 'muscle' => 'glutes', 'secondary' => ['hamstrings'], 'equipment' => 'bodyweight_only', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Acostado boca arriba, empuja la cadera hacia arriba apretando los glúteos.',
                'common_mistakes' => 'No llegar a la extensión completa de cadera.',
                'tips' => 'Buen punto de partida antes de progresar al hip thrust con carga.'],
            ['name' => 'Patada de glúteo en polea', 'muscle' => 'glutes', 'secondary' => [], 'equipment' => 'cables', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Con el tobillo en la polea baja, extiende la pierna hacia atrás.',
                'common_mistakes' => 'Usar impulso en la espalda baja.',
                'tips' => 'Aísla bien el glúteo con tensión constante.'],
            ['name' => 'Abducción de cadera en máquina', 'muscle' => 'glutes', 'secondary' => [], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Empuja las piernas hacia afuera contra la resistencia de la máquina.',
                'common_mistakes' => 'Inclinar el torso para ayudar con impulso.',
                'tips' => 'Trabaja el glúteo medio, importante para estabilidad de cadera.'],
            ['name' => 'Swing con kettlebell', 'muscle' => 'glutes', 'secondary' => ['hamstrings', 'core'], 'equipment' => 'kettlebells', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Con un movimiento de bisagra de cadera, impulsa la kettlebell hacia adelante hasta la altura del pecho.',
                'common_mistakes' => 'Usar los brazos para levantar en lugar de la cadera.',
                'tips' => 'Ejercicio explosivo excelente para glúteos y acondicionamiento.'],

            // ---- Core ----
            ['name' => 'Plancha', 'muscle' => 'core', 'secondary' => [], 'equipment' => 'bodyweight_only', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Mantén el cuerpo en línea recta apoyado en antebrazos y pies.',
                'common_mistakes' => 'Dejar caer la cadera o elevar demasiado los glúteos.',
                'tips' => 'Aprieta el abdomen como si fueras a recibir un golpe.'],
            ['name' => 'Crunch abdominal', 'muscle' => 'core', 'secondary' => [], 'equipment' => 'bodyweight_only', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Flexiona el torso llevando las costillas hacia la pelvis.',
                'common_mistakes' => 'Tirar del cuello con las manos.',
                'tips' => 'Movimiento corto y controlado, no es necesario sentarse completo.'],
            ['name' => 'Elevación de piernas colgado', 'muscle' => 'core', 'secondary' => [], 'equipment' => 'pull_up_bar', 'level' => 'advanced', 'type' => 'isolation',
                'instructions' => 'Colgado de la barra, eleva las piernas hacia el pecho sin balancearte.',
                'common_mistakes' => 'Usar impulso balanceando el cuerpo.',
                'tips' => 'Progresión avanzada; empieza con rodillas flexionadas si es necesario.'],
            ['name' => 'Rueda abdominal', 'muscle' => 'core', 'secondary' => ['shoulders'], 'equipment' => 'bodyweight_only', 'level' => 'advanced', 'type' => 'isolation',
                'instructions' => 'Desde rodillas, rueda hacia adelante manteniendo el core apretado y vuelve al inicio.',
                'common_mistakes' => 'Arquear la espalda baja al extenderse.',
                'tips' => 'Exige core muy fuerte; progresa gradualmente el rango.'],
            ['name' => 'Russian twist', 'muscle' => 'core', 'secondary' => [], 'equipment' => 'bodyweight_only', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Sentado con el torso inclinado, rota de lado a lado tocando el suelo.',
                'common_mistakes' => 'Mover solo los brazos en lugar de rotar el torso.',
                'tips' => 'Añade peso (mancuerna o balón) para progresar.'],
            ['name' => 'Crunch en polea', 'muscle' => 'core', 'secondary' => [], 'equipment' => 'cables', 'level' => 'intermediate', 'type' => 'isolation',
                'instructions' => 'De rodillas frente a la polea alta, flexiona el torso hacia abajo contrayendo el abdomen.',
                'common_mistakes' => 'Tirar con los brazos en lugar de flexionar con el abdomen.',
                'tips' => 'Permite sobrecargar el abdomen progresivamente con peso externo.'],
            ['name' => 'Plancha lateral', 'muscle' => 'core', 'secondary' => [], 'equipment' => 'bodyweight_only', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Apoyado en un antebrazo, mantén el cuerpo en línea recta de lado.',
                'common_mistakes' => 'Dejar caer la cadera hacia el suelo.',
                'tips' => 'Trabaja los oblicuos, importantes para estabilidad del tronco.'],

            // ---- Pantorrillas ----
            ['name' => 'Elevación de talones de pie', 'muscle' => 'calves', 'secondary' => [], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Eleva los talones lo más alto posible y baja controlado hasta estirar.',
                'common_mistakes' => 'Hacer el movimiento demasiado rápido, perdiendo rango.',
                'tips' => 'Pausa arriba un segundo para maximizar la contracción.'],
            ['name' => 'Elevación de talones sentado', 'muscle' => 'calves', 'secondary' => [], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Con las rodillas flexionadas, eleva los talones contra la resistencia.',
                'common_mistakes' => 'Rango de movimiento incompleto.',
                'tips' => 'Con la rodilla flexionada se enfatiza más el sóleo.'],
            ['name' => 'Elevación de talones con mancuernas', 'muscle' => 'calves', 'secondary' => [], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'De pie sobre un escalón, eleva los talones sosteniendo mancuernas.',
                'common_mistakes' => 'No bajar lo suficiente para estirar la pantorrilla.',
                'tips' => 'Usa un escalón para aumentar el rango de movimiento.'],

            // ---- Plantillas de rutina (sexo x frecuencia) — ejercicios que
            // faltaban en el catálogo base para cubrir las listas curadas de
            // RoutineTemplateSeeder. El resto de esos ejercicios ya existían
            // arriba y se reutilizan por nombre.
            ['name' => 'Press inclinado en máquina', 'muscle' => 'chest', 'secondary' => ['shoulders', 'triceps'], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Empuja las manijas hacia arriba y adelante en trayectoria inclinada.',
                'common_mistakes' => 'Ajustar mal la altura del asiento respecto al agarre.',
                'tips' => 'Buena alternativa estable al press inclinado con mancuernas.'],
            ['name' => 'Aperturas en máquina', 'muscle' => 'chest', 'secondary' => [], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Junta las manijas al frente del pecho en un arco controlado (Pec Deck).',
                'common_mistakes' => 'Usar demasiado peso y perder el rango final.',
                'tips' => 'Mantén una ligera flexión de codo constante durante todo el recorrido.'],
            ['name' => 'Vuelos posteriores en polea', 'muscle' => 'shoulders', 'secondary' => ['back'], 'equipment' => 'cables', 'level' => 'intermediate', 'type' => 'isolation',
                'instructions' => 'Con las poleas cruzadas a la altura del pecho, abre los brazos hacia atrás.',
                'common_mistakes' => 'Usar los brazos en vez de los deltoides posteriores para tirar.',
                'tips' => 'Tensión constante en todo el recorrido, a diferencia de la mancuerna.'],
            ['name' => 'Tríceps en máquina', 'muscle' => 'triceps', 'secondary' => [], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Empuja las manijas hacia abajo/adelante extendiendo los codos.',
                'common_mistakes' => 'Separar los codos del cuerpo.',
                'tips' => 'Buena opción para llegar al fallo con seguridad.'],
            ['name' => 'Katana en polea', 'muscle' => 'triceps', 'secondary' => [], 'equipment' => 'cables', 'level' => 'intermediate', 'type' => 'isolation',
                'instructions' => 'De espaldas a la polea alta, extiende un brazo por encima de la cabeza hacia adelante.',
                'common_mistakes' => 'Mover el hombro en vez de aislar el codo.',
                'tips' => 'Enfatiza la cabeza larga del tríceps por el ángulo sobre la cabeza.'],
            ['name' => 'Rompecráneos a dos manos con mancuerna', 'muscle' => 'triceps', 'secondary' => [], 'equipment' => 'dumbbells', 'level' => 'intermediate', 'type' => 'isolation',
                'instructions' => 'Acostado, baja una mancuerna con ambas manos hacia la frente flexionando los codos.',
                'common_mistakes' => 'Abrir los codos hacia afuera durante el descenso.',
                'tips' => 'Controla bien el peso cerca de la cabeza.'],
            ['name' => 'Jalón en polea alta', 'muscle' => 'back', 'secondary' => ['biceps'], 'equipment' => 'cables', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Tira de la barra ancha hacia la parte superior del pecho.',
                'common_mistakes' => 'Tirar con los brazos en vez de iniciar con la espalda.',
                'tips' => 'Buena progresión antes de dominadas completas.'],
            ['name' => 'Pull over en polea', 'muscle' => 'back', 'secondary' => ['chest'], 'equipment' => 'cables', 'level' => 'intermediate', 'type' => 'isolation',
                'instructions' => 'Con los brazos casi extendidos, lleva la barra desde arriba hacia los muslos.',
                'common_mistakes' => 'Flexionar demasiado los codos, convirtiéndolo en un jalón.',
                'tips' => 'Trabaja dorsal ancho con tensión constante.'],
            ['name' => 'Jalón en polea con agarre cerrado', 'muscle' => 'back', 'secondary' => ['biceps'], 'equipment' => 'cables', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Con agarre estrecho neutro, tira de la barra hacia el pecho.',
                'common_mistakes' => 'Balancear el torso hacia atrás para ayudar con impulso.',
                'tips' => 'El agarre cerrado enfatiza más la porción baja del dorsal.'],
            ['name' => 'Peso muerto rumano en Smith', 'muscle' => 'back', 'secondary' => ['hamstrings', 'glutes'], 'equipment' => 'machines', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'Con la barra guiada del Smith, baja pegada a las piernas con ligera flexión de rodilla.',
                'common_mistakes' => 'Redondear la espalda baja al bajar.',
                'tips' => 'El riel del Smith facilita mantener la trayectoria recta.'],
            ['name' => 'Curl bayesiano en polea', 'muscle' => 'biceps', 'secondary' => [], 'equipment' => 'cables', 'level' => 'intermediate', 'type' => 'isolation',
                'instructions' => 'De espaldas a la polea baja, flexiona el codo con el brazo detrás del torso.',
                'common_mistakes' => 'Adelantar el codo durante el movimiento.',
                'tips' => 'La posición detrás del cuerpo maximiza el estiramiento del bíceps.'],
            ['name' => 'Curl bayesiano con mancuerna en banco', 'muscle' => 'biceps', 'secondary' => [], 'equipment' => 'dumbbells', 'level' => 'intermediate', 'type' => 'isolation',
                'instructions' => 'Con el brazo detrás del torso apoyado en un banco inclinado, flexiona el codo.',
                'common_mistakes' => 'Perder la posición del codo detrás del cuerpo.',
                'tips' => 'Alternativa sin polea al curl bayesiano.'],
            ['name' => 'Curl predicador en máquina', 'muscle' => 'biceps', 'secondary' => [], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Con los brazos apoyados en el soporte, flexiona los codos hacia los hombros.',
                'common_mistakes' => 'Extender completamente el codo bajo carga.',
                'tips' => 'Estable y fácil de dosificar el peso.'],
            ['name' => 'Curl predicador con mancuerna en banco', 'muscle' => 'biceps', 'secondary' => [], 'equipment' => 'dumbbells', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Con el tríceps apoyado en un banco Scott, flexiona el codo con una mancuerna.',
                'common_mistakes' => 'Despegar el brazo del soporte.',
                'tips' => 'Permite trabajar cada brazo de forma independiente.'],
            ['name' => 'Sentadilla en Smith', 'muscle' => 'quads', 'secondary' => ['glutes'], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Con la barra guiada del Smith sobre los hombros, baja controlado en sentadilla.',
                'common_mistakes' => 'Colocar los pies demasiado cerca de la trayectoria de la barra.',
                'tips' => 'El riel guiado facilita enfocarse en la profundidad y el control.'],
            ['name' => 'Sentadilla Hack', 'muscle' => 'quads', 'secondary' => ['glutes'], 'equipment' => 'machines', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'En la máquina hack, baja la cadera manteniendo la espalda apoyada.',
                'common_mistakes' => 'Bajar más allá del rango cómodo de la máquina.',
                'tips' => 'Gran énfasis en cuádriceps con baja demanda de estabilización.'],
            ['name' => 'Sentadilla Sissy', 'muscle' => 'quads', 'secondary' => [], 'equipment' => 'bodyweight_only', 'level' => 'advanced', 'type' => 'isolation',
                'instructions' => 'Sosteniéndote de un soporte, inclina las rodillas hacia adelante bajando el torso recto.',
                'common_mistakes' => 'Perder el equilibrio por falta de sujeción.',
                'tips' => 'Aislamiento intenso de cuádriceps; progresa gradualmente.'],
            ['name' => 'Prensa horizontal', 'muscle' => 'quads', 'secondary' => ['glutes'], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Empuja la plataforma horizontal extendiendo las piernas sin bloquear rodillas.',
                'common_mistakes' => 'Rango de movimiento incompleto.',
                'tips' => 'Variante de la prensa con otro ángulo de carga sobre el cuádriceps.'],
            ['name' => 'Zancada en Smith', 'muscle' => 'quads', 'secondary' => ['glutes'], 'equipment' => 'machines', 'level' => 'intermediate', 'type' => 'compound',
                'instructions' => 'Con la barra guiada del Smith, da un paso atrás/adelante bajando en zancada.',
                'common_mistakes' => 'Perder el equilibrio lateral durante el movimiento.',
                'tips' => 'El riel guiado da más estabilidad que la zancada libre.'],
            ['name' => 'Femoral sentado en máquina', 'muscle' => 'hamstrings', 'secondary' => [], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Sentado, flexiona las rodillas llevando los talones hacia abajo/atrás.',
                'common_mistakes' => 'Levantar los muslos del asiento.',
                'tips' => 'Complementa al femoral acostado con otro ángulo de tensión.'],
            ['name' => 'Hip Thrust en máquina', 'muscle' => 'glutes', 'secondary' => ['hamstrings'], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'compound',
                'instructions' => 'Con la espalda apoyada, empuja la cadera hacia arriba contra la resistencia de la máquina.',
                'common_mistakes' => 'Hiperextender la espalda baja en vez de usar los glúteos.',
                'tips' => 'Más fácil de dosificar el peso que la barra libre.'],
            ['name' => 'Patada de glúteo en máquina', 'muscle' => 'glutes', 'secondary' => [], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Empuja la plataforma hacia atrás extendiendo la cadera, una pierna a la vez.',
                'common_mistakes' => 'Usar impulso en la espalda baja.',
                'tips' => 'Alternativa estable a la patada en polea.'],
            ['name' => 'Abducción en polea', 'muscle' => 'glutes', 'secondary' => [], 'equipment' => 'cables', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Con el tobillo en la polea baja, aleja la pierna del cuerpo lateralmente.',
                'common_mistakes' => 'Inclinar el torso para ayudar con impulso.',
                'tips' => 'Tensión constante en todo el recorrido del glúteo medio.'],
            ['name' => 'Aductores en máquina', 'muscle' => 'glutes', 'secondary' => [], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'Junta las piernas contra la resistencia de la máquina.',
                'common_mistakes' => 'Rango de movimiento incompleto.',
                'tips' => 'Complementa el trabajo de abductores para equilibrio de cadera.'],
            ['name' => 'Pantorrilla sentado en prensa', 'muscle' => 'calves', 'secondary' => [], 'equipment' => 'machines', 'level' => 'beginner', 'type' => 'isolation',
                'instructions' => 'En la prensa de piernas, empuja la plataforma solo con la punta de los pies.',
                'common_mistakes' => 'Rango de movimiento incompleto.',
                'tips' => 'Aprovecha el equipo de piernas sin necesitar máquina dedicada.'],
        ];

        foreach ($exercises as $data) {
            $secondary = $data['secondary'];

            $exercise = Exercise::query()->updateOrCreate(
                ['name' => $data['name']],
                [
                    'primary_muscle_id' => $muscles[$data['muscle']],
                    'equipment' => $data['equipment'],
                    'level' => $data['level'],
                    'type' => $data['type'],
                    'instructions' => $data['instructions'],
                    'common_mistakes' => $data['common_mistakes'],
                    'tips' => $data['tips'],
                    'is_active' => true,
                ],
            );

            if ($secondary !== []) {
                $exercise->secondaryMuscles()->sync(
                    collect($secondary)->map(fn (string $slug) => $muscles[$slug])->all()
                );
            }
        }
    }
}
