import type { LegalDocumentContent } from '../types';

/**
 * Privacy Policy — English translation of privacy.es.ts.
 * NOT legally reviewed: the Spanish text is the reference version. Keep both
 * in sync (same sections, same facts) whenever either changes.
 */
export const privacyEn: LegalDocumentContent = {
  title: 'Privacy Policy',
  summary: 'What personal data {{brandName}} processes, why, who it is shared with, and how you can exercise your rights.',
  sections: [
    {
      id: 'responsable',
      title: '1. Data controller',
      blocks: [
        {
          type: 'p',
          text: 'The controller of your personal data in {{brandName}} is {{legalName}}, identified by {{taxId}}, with address at {{address}} ({{country}}).',
        },
        { type: 'p', text: 'For any privacy question or request, write to {{privacyEmail}}.' },
      ],
    },
    {
      id: 'datos',
      title: '2. What data we process',
      blocks: [
        {
          type: 'p',
          text: 'We only process the data the app needs for the features you use. Depending on how you use {{brandName}}, this may include:',
        },
        {
          type: 'table',
          headers: ['Category', 'Data', 'Source'],
          rows: [
            [
              'Account',
              'Name, email, password (stored only as a hash, never in plain text), phone number if you provide it, profile photo if you upload one, role (user or trainer) and email verification date.',
              'You, when signing up or editing your profile.',
            ],
            [
              'Sign in with Google',
              'Name, email, whether the email is verified, Google profile photo and a Firebase technical identifier.',
              'Google / Firebase, only if you choose "Continue with Google".',
            ],
            [
              'Account security',
              'Two-step verification settings (encrypted secret and recovery codes), active sessions with the name of the browser or device they were started from, last activity date and a log of sign-ins (date and whether it was web or mobile).',
              'Generated by the app as you use it.',
            ],
            [
              'Training profile',
              'Age, sex, height, weight, experience level, goals, days per week available to train, available equipment, country, department/state, city and gym.',
              'You, in the initial questionnaire and in settings.',
            ],
            [
              'Workouts and progress',
              'Assigned or generated routines, completed, skipped or cancelled sessions, exercises, sets (weight, reps, perceived effort), duration, notes and ratings, personal records, achievements, experience points (XP), streaks, challenges, calendar and reminders.',
              'You, when logging activity, and the app when calculating your progress.',
            ],
            [
              'Pre-workout status',
              'Sleep quality, energy level and muscle soreness you report before training, and the resulting session adjustment.',
              'You, in the optional pre-workout check.',
            ],
            [
              'Body measurements',
              'Weight, body fat percentage and circumferences (chest, waist, hip, arm, thigh) with their date.',
              'You, if you choose to log them.',
            ],
            [
              'Nutrition',
              'Logged meals (food, quantity, meal type and date), nutrition plan, calculated calorie and macronutrient targets, food searches and scanned barcodes.',
              'You, in the nutrition section.',
            ],
            [
              'Records with video',
              'Exercise, weight, reps and the video you submit to validate a record, and the review result.',
              'You, if you submit a record for validation.',
            ],
            [
              'Communications',
              'Chat messages with your trainer or your clients (content and read status), content reports you submit and in-app notifications.',
              'You and the people you talk to.',
            ],
            [
              'Store orders',
              'Name, email, phone, WhatsApp number, department, city, address, additional information, products, amounts, order status, carrier and tracking number.',
              'You, when placing an order; the {{brandName}} team, when managing it.',
            ],
            [
              'Push notifications',
              'Device notification identifier (mobile app) or browser subscription data (web), only if you turn notifications on.',
              'Your device or browser, with your permission.',
            ],
          ],
        },
        {
          type: 'note',
          text: '{{brandName}} does not process online payments or store card details. We do not use third-party analytics tools or advertising.',
        },
        {
          type: 'p',
          text: 'IP address: the server processes it technically to answer your requests and to limit repeated attempts (for example, sign-in attempts) as an anti-abuse measure. It may appear in the technical logs of the server and of the connection tunnels (see section 6). We do not link it to your profile or use it for advertising.',
        },
      ],
    },
    {
      id: 'finalidades',
      title: '3. Why we use your data',
      blocks: [
        {
          type: 'list',
          items: [
            'To create and manage your account and authenticate you (including email verification, password recovery and two-step verification if you enable it).',
            'To generate and adjust your routines based on your profile, level, goals, availability, equipment and pre-workout status.',
            'To log your workouts and show your progress, records, statistics, achievements, streaks and challenges.',
            'To calculate guidance nutrition targets and log your meals.',
            'To enable communication with your trainer (or your clients, if you are a trainer).',
            'To show you in public rankings only if you turn on "Public rankings" (you can turn it off at any time), and in the leaderboards of challenges you join.',
            'To review records you submit with video and content reports.',
            'To manage and deliver your store orders and contact you about them.',
            'To send you push notifications when you have enabled them, and transactional emails (email verification, password recovery).',
            'To keep the service secure, prevent abuse and fraud, and enforce the Terms and Conditions.',
            'To obtain internal, aggregated usage statistics (for example, how many people use the app each day and from which platform) to operate and improve the service. These are calculated from our own records, without third-party tools.',
          ],
        },
        {
          type: 'p',
          text: 'Legal basis: processing is based on your prior, express and informed authorization (in particular for health and fitness data, which are sensitive data), on providing the service you request when accepting the Terms and Conditions, and on the need to keep the service secure, under Law 1581 of 2012 of {{jurisdiction}} and its implementing regulations.',
        },
      ],
    },
    {
      id: 'salud',
      title: '4. Health and fitness data',
      blocks: [
        {
          type: 'p',
          text: 'Some data you log in {{brandName}} (weight, height, age, sex, body composition and measurements, sleep quality, energy, muscle soreness and diet) may be considered health-related or sensitive data under applicable law. That is why we ask for a specific, separate authorization to process it.',
        },
        {
          type: 'list',
          items: [
            'We use it only to personalize your routines and nutrition targets and to show your progress.',
            'We do not sell it or use it for advertising.',
            'It is only visible to your trainer if you connect with one in the app, and to the {{brandName}} administration team when needed for support, moderation or security.',
            'It is optional to the extent that you may skip logging measurements, the pre-workout check or the nutrition section; without some of it (for example level, goals or weight) the app cannot generate a personalized routine.',
          ],
        },
        {
          type: 'note',
          text: '{{brandName}} is a training and tracking tool. It does not provide medical services, does not diagnose, and does not replace advice from a doctor, dietitian or other health professional.',
        },
      ],
    },
    {
      id: 'destinatarios',
      title: '5. Who we share your data with',
      blocks: [
        { type: 'p', text: 'We do not sell your data. It is only shared in these cases:' },
        {
          type: 'list',
          items: [
            'Your trainer: if you connect with a trainer in {{brandName}}, they can see what they need to coach you (your name, routines, workouts and progress) and chat with you.',
            'Other users: your name and lifts appear in rankings only if you turn on "Public rankings"; in challenges you join, your name and progress appear in the challenge leaderboard.',
            '{{brandName}} administration team: limited access to what is needed for support, moderation, record review and order management.',
            'Technical providers that provide services to {{brandName}} (see section 6), only with the data each one needs.',
            'Shipping companies: when applicable, the carrier delivering your order receives the delivery name, phone and address.',
            'Authorities: when required by law or by an order of a competent authority.',
          ],
        },
      ],
    },
    {
      id: 'terceros',
      title: '6. Third-party services',
      blocks: [
        {
          type: 'table',
          headers: ['Service', 'Purpose', 'Information it may receive'],
          rows: [
            [
              'Google (Firebase Authentication and Google Sign-In)',
              'Signing in or up with your Google account, only if you choose that option.',
              'The Google account data you authorize sharing (name, email, photo) and technical connection data. Google processes it under its own privacy policy.',
            ],
            ['Google Fonts (web only)', 'Loading the interface typeface.', 'Your IP address and technical browser data when downloading the font.'],
            [
              'Expo push notification service (mobile app)',
              'Delivering push notifications to your phone, through Firebase Cloud Messaging (Google) or Apple Push Notification service.',
              'Your device notification identifier and the notification content (for example, the sender name and the beginning of the message).',
            ],
            [
              'Your browser push service (web)',
              'Delivering browser notifications, if you enable them.',
              'An encrypted notification; the provider depends on your browser (for example Google, Mozilla or Apple).',
            ],
            [
              'Open Food Facts',
              'Looking up food nutrition information by name or barcode.',
              'Only the search text or barcode. The request is made by the {{brandName}} server, without data that identifies you.',
            ],
            ['{{emailProvider}}', 'Sending verification and password recovery emails.', 'Your email address and the message content.'],
            [
              'ngrok and Cloudflare (connection tunnels)',
              'Today the {{brandName}} server (database and files) runs on equipment owned by the controller, with no external hosting provider, and is connected to the Internet through these tunnels.',
              'Traffic between the app and the server passes through them, including the data you send and receive. If a hosting provider is hired, it will be disclosed in a new version of this policy.',
            ],
            ['WhatsApp (Meta)', 'Only if you choose to contact us via WhatsApp from the app.', 'The conversation happens in WhatsApp and is governed by its policies.'],
          ],
        },
        {
          type: 'p',
          text: 'Some of these providers may process data outside your country. When that happens, the safeguards required by the law applicable in {{jurisdiction}} will apply.',
        },
      ],
    },
    {
      id: 'conservacion',
      title: '7. How long we keep your data',
      blocks: [
        {
          type: 'p',
          text: 'We keep your data while your account is active. If your account is deleted, the data linked to it (profile, workouts, measurements, nutrition, messages, notifications and consents) is deleted too, unless the law requires keeping it longer. The internal audit log of administrative actions may keep references to the account for security reasons. Specific periods: {{retentionPeriod}}.',
        },
        {
          type: 'p',
          text: 'We keep a record of which version of each legal document you accepted and when, as proof of your consent, for as long as your account exists.',
        },
      ],
    },
    {
      id: 'derechos',
      title: '8. Your rights',
      blocks: [
        { type: 'p', text: 'Under Colombian personal data protection law (Law 1581 of 2012 and its implementing regulations), you can:' },
        {
          type: 'list',
          items: [
            'Find out what data about you we process and get a copy.',
            'Ask us to correct inaccurate or incomplete data. You can correct much of it yourself from the app settings.',
            'Delete your account and your data at any time from Settings > Delete my account, or ask us to delete specific data, where applicable.',
            'Withdraw your consent where processing is based on it. Withdrawal does not affect prior processing and may prevent us from continuing to provide features that depend on that data.',
            'Request information about how we use your data and about this policy.',
            'File a complaint with {{supervisoryAuthority}}, after first submitting your query or claim to us.',
          ],
        },
        {
          type: 'p',
          text: 'To exercise any of these rights, write to {{privacyEmail}} from the email linked to your account, stating your request. We may ask for additional information to verify your identity before handling it.',
        },
        {
          type: 'p',
          text: 'From the app settings you can also, at any time: turn your appearance in public rankings on or off, turn push notifications on or off and, on the web, change your cookie preferences.',
        },
      ],
    },
    {
      id: 'seguridad',
      title: '9. Security',
      blocks: [
        {
          type: 'list',
          items: [
            'Passwords are stored with a cryptographic hash, never in plain text.',
            'You can enable two-step verification; its secret is stored encrypted.',
            'Access to information is limited by role (user, trainer, administration).',
            'Repeated sign-in and sign-up attempts are automatically rate-limited.',
          ],
        },
        {
          type: 'p',
          text: 'No system is completely infallible. If we detect a security incident affecting your data, we will act as required by applicable law.',
        },
      ],
    },
    {
      id: 'menores',
      title: '10. Minors',
      blocks: [
        {
          type: 'p',
          text: 'The app requires a minimum age of 13. To use {{brandName}} without an adult\'s authorization you must be at least {{minimumAge}}. If you are younger, you need authorization from your parent or legal guardian.',
        },
      ],
    },
    {
      id: 'cookies',
      title: '11. Cookies and local storage',
      blocks: [
        {
          type: 'p',
          text: 'The web version uses cookies and browser local storage. Details are in the Cookie Policy. The mobile app keeps your session and some preferences in the phone\'s secure storage; it does not use tracking or advertising cookies.',
        },
      ],
    },
    {
      id: 'cambios',
      title: '12. Changes to this policy',
      blocks: [
        {
          type: 'p',
          text: 'Each version of this policy has a number and a date. If we make important changes, we will ask you to review and accept the new version before you keep using the app.',
        },
      ],
    },
  ],
};
