// Esta línea sirve para importar el tipo del contenido de un documento legal.
import type { LegalDocumentContent } from '../types';

/**
 * Privacy Policy — English translation of privacy.es.ts.
 * Reviewed by the SanKen owner; the Spanish text is the reference version. Keep both
 * in sync (same sections, same facts) whenever either changes.
 */
// Esta línea sirve para declarar el contenido del documento legal "privacyEn".
export const privacyEn: LegalDocumentContent = {
  // Esta línea sirve para definir el título del documento: «Privacy Policy».
  title: 'Privacy Policy',
  // Esta línea sirve para definir el resumen del documento: «What personal data {{brandName}} processes, why, who it is s…».
  summary: 'What personal data {{brandName}} processes, why, who it is shared with, and how you can exercise your rights.',
  // Esta línea sirve para abrir la lista de secciones del documento.
  sections: [
    {
      // Esta línea sirve para identificar la sección con el id "responsable".
      id: 'responsable',
      // Esta línea sirve para definir el título de la sección: «1. Data controller».
      title: '1. Data controller',
      // Esta línea sirve para abrir los bloques de contenido de la sección.
      blocks: [
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «The controller of your personal data in {{brandName}} is {{legalName}}…».
          text: 'The controller of your personal data in {{brandName}} is {{legalName}}, identified by {{taxId}}, with address at {{address}} ({{country}}).',
        },
        // Esta línea sirve para incluir el párrafo con el correo para dudas de privacidad.
        { type: 'p', text: 'For any privacy question or request, write to {{privacyEmail}}.' },
      ],
    },
    {
      // Esta línea sirve para identificar la sección con el id "datos".
      id: 'datos',
      // Esta línea sirve para definir el título de la sección: «2. What data we process».
      title: '2. What data we process',
      // Esta línea sirve para abrir los bloques de contenido de la sección.
      blocks: [
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «We only process the data the app needs for the features you use. Depen…».
          text: 'We only process the data the app needs for the features you use. Depending on how you use {{brandName}}, this may include:',
        },
        {
          // Esta línea sirve para indicar que el bloque es una tabla.
          type: 'table',
          // Esta línea sirve para definir los encabezados de la tabla.
          headers: ['Category', 'Data', 'Source'],
          // Esta línea sirve para abrir las filas de la tabla.
          rows: [
            [
              // Esta línea sirve para agregar la celda de la fila: «Account…».
              'Account',
              // Esta línea sirve para agregar la celda de la fila: «Name, email, password (stored only as a hash, neve…».
              'Name, email, password (stored only as a hash, never in plain text), phone number if you provide it, profile photo if you upload one, role (user or trainer) and email verification date.',
              // Esta línea sirve para agregar la celda de la fila: «You, when signing up or editing your profile.…».
              'You, when signing up or editing your profile.',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Sign in with Google…».
              'Sign in with Google',
              // Esta línea sirve para agregar la celda de la fila: «Name, email, whether the email is verified, Google…».
              'Name, email, whether the email is verified, Google profile photo and a Firebase technical identifier.',
              // Esta línea sirve para agregar la celda de la fila: «Google / Firebase, only if you choose "Continue wi…».
              'Google / Firebase, only if you choose "Continue with Google".',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Account security…».
              'Account security',
              // Esta línea sirve para agregar la celda de la fila: «Two-step verification settings (encrypted secret a…».
              'Two-step verification settings (encrypted secret and recovery codes), active sessions with the name of the browser or device they were started from, last activity date and a log of sign-ins (date and whether it was web or mobile).',
              // Esta línea sirve para agregar la celda de la fila: «Generated by the app as you use it.…».
              'Generated by the app as you use it.',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Training profile…».
              'Training profile',
              // Esta línea sirve para agregar la celda de la fila: «Age, sex, height, weight, experience level, goals,…».
              'Age, sex, height, weight, experience level, goals, days per week available to train, available equipment, country, department/state, city and gym.',
              // Esta línea sirve para agregar la celda de la fila: «You, in the initial questionnaire and in settings.…».
              'You, in the initial questionnaire and in settings.',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Workouts and progress…».
              'Workouts and progress',
              // Esta línea sirve para agregar la celda de la fila: «Assigned or generated routines, completed, skipped…».
              'Assigned or generated routines, completed, skipped or cancelled sessions, exercises, sets (weight, reps, perceived effort), duration, notes and ratings, personal records, achievements, experience points (XP), streaks, challenges, calendar and reminders.',
              // Esta línea sirve para agregar la celda de la fila: «You, when logging activity, and the app when calcu…».
              'You, when logging activity, and the app when calculating your progress.',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Pre-workout status…».
              'Pre-workout status',
              // Esta línea sirve para agregar la celda de la fila: «Sleep quality, energy level and muscle soreness yo…».
              'Sleep quality, energy level and muscle soreness you report before training, and the resulting session adjustment.',
              // Esta línea sirve para agregar la celda de la fila: «You, in the optional pre-workout check.…».
              'You, in the optional pre-workout check.',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Body measurements…».
              'Body measurements',
              // Esta línea sirve para agregar la celda de la fila: «Weight, body fat percentage and circumferences (ch…».
              'Weight, body fat percentage and circumferences (chest, waist, hip, arm, thigh) with their date.',
              // Esta línea sirve para agregar la celda de la fila: «You, if you choose to log them.…».
              'You, if you choose to log them.',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Nutrition…».
              'Nutrition',
              // Esta línea sirve para agregar la celda de la fila: «Logged meals (food, quantity, meal type and date),…».
              'Logged meals (food, quantity, meal type and date), nutrition plan, calculated calorie and macronutrient targets, food searches and scanned barcodes.',
              // Esta línea sirve para agregar la celda de la fila: «You, in the nutrition section.…».
              'You, in the nutrition section.',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Records with video…».
              'Records with video',
              // Esta línea sirve para agregar la celda de la fila: «Exercise, weight, reps and the video you submit to…».
              'Exercise, weight, reps and the video you submit to validate a record, and the review result.',
              // Esta línea sirve para agregar la celda de la fila: «You, if you submit a record for validation.…».
              'You, if you submit a record for validation.',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Communications…».
              'Communications',
              // Esta línea sirve para agregar la celda de la fila: «Chat messages with your trainer or your clients (c…».
              'Chat messages with your trainer or your clients (content and read status), content reports you submit and in-app notifications.',
              // Esta línea sirve para agregar la celda de la fila: «You and the people you talk to.…».
              'You and the people you talk to.',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Support…».
              'Support',
              // Esta línea sirve para agregar la celda de la fila: «Requests you send to the {{brandName}} team (type,…».
              'Requests you send to the {{brandName}} team (type, subject, messages and status) and the team replies.',
              // Esta línea sirve para agregar la celda de la fila: «You, in the Support section.…».
              'You, in the Support section.',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Weekly check-in…».
              'Weekly check-in',
              // Esta línea sirve para agregar la celda de la fila: «How you felt about your workouts that week, whethe…».
              'How you felt about your workouts that week, whether you wanted to tell us something (and your comment, if you wrote one), whether you postponed it and, as context, your active routine and how many sessions you completed that week.',
              // Esta línea sirve para agregar la celda de la fila: «You, when answering the check-in (optional).…».
              'You, when answering the check-in (optional).',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Store orders…».
              'Store orders',
              // Esta línea sirve para agregar la celda de la fila: «Name, email, phone, WhatsApp number, department, c…».
              'Name, email, phone, WhatsApp number, department, city, address, additional information, products, amounts, order status, carrier and tracking number.',
              // Esta línea sirve para agregar la celda de la fila: «You, when placing an order; the {{brandName}} team…».
              'You, when placing an order; the {{brandName}} team, when managing it.',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Push notifications…».
              'Push notifications',
              // Esta línea sirve para agregar la celda de la fila: «Device notification identifier (mobile app) or bro…».
              'Device notification identifier (mobile app) or browser subscription data (web), only if you turn notifications on.',
              // Esta línea sirve para agregar la celda de la fila: «Your device or browser, with your permission.…».
              'Your device or browser, with your permission.',
            ],
          ],
        },
        {
          // Esta línea sirve para indicar que el bloque es una nota destacada.
          type: 'note',
          // Esta línea sirve para incluir el texto: «{{brandName}} does not process online payments or store card details. …».
          text: '{{brandName}} does not process online payments or store card details. We do not use third-party analytics tools or advertising.',
        },
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «IP address: the server processes it technically to answer your request…».
          text: 'IP address: the server processes it technically to answer your requests and to limit repeated attempts (for example, sign-in attempts) as an anti-abuse measure. It may appear in the technical logs of the server and of the connection tunnels (see section 6). We do not link it to your profile or use it for advertising.',
        },
      ],
    },
    {
      // Esta línea sirve para identificar la sección con el id "finalidades".
      id: 'finalidades',
      // Esta línea sirve para definir el título de la sección: «3. Why we use your data».
      title: '3. Why we use your data',
      // Esta línea sirve para abrir los bloques de contenido de la sección.
      blocks: [
        {
          // Esta línea sirve para indicar que el bloque es una lista.
          type: 'list',
          // Esta línea sirve para abrir los ítems de la lista.
          items: [
            // Esta línea sirve para agregar el ítem: «To create and manage your account and authenticate you (incl…».
            'To create and manage your account and authenticate you (including email verification, password recovery and two-step verification if you enable it).',
            // Esta línea sirve para agregar el ítem: «To generate and adjust your routines based on your profile, …».
            'To generate and adjust your routines based on your profile, level, goals, availability, equipment and pre-workout status.',
            // Esta línea sirve para agregar el ítem: «To log your workouts and show your progress, records, statis…».
            'To log your workouts and show your progress, records, statistics, achievements, streaks and challenges.',
            // Esta línea sirve para agregar el ítem: «To calculate guidance nutrition targets and log your meals.…».
            'To calculate guidance nutrition targets and log your meals.',
            // Esta línea sirve para agregar el ítem: «To enable communication with your trainer (or your clients, …».
            'To enable communication with your trainer (or your clients, if you are a trainer).',
            // Esta línea sirve para agregar el ítem: «To show you in public rankings only if you turn on "Public r…».
            'To show you in public rankings only if you turn on "Public rankings" (you can turn it off at any time), and in the leaderboards of challenges you join.',
            // Esta línea sirve para agregar el ítem: «To review records you submit with video and content reports.…».
            'To review records you submit with video and content reports.',
            // Esta línea sirve para agregar el ítem: «To handle your support requests (questions, complaints, obse…».
            'To handle your support requests (questions, complaints, observations, suggestions or problems) and reply to you.',
            // Esta línea sirve para agregar el ítem: «To ask you once a week how you felt about your workouts, to …».
            'To ask you once a week how you felt about your workouts, to detect questions or problems and improve routines. Today your answers do not change your routine automatically; if they are used to adjust it in the future, this policy will say so.',
            // Esta línea sirve para agregar el ítem: «To manage and deliver your store orders and contact you abou…».
            'To manage and deliver your store orders and contact you about them.',
            // Esta línea sirve para agregar el ítem: «To send you push notifications when you have enabled them, a…».
            'To send you push notifications when you have enabled them, and transactional emails (email verification, password recovery).',
            // Esta línea sirve para agregar el ítem: «To keep the service secure, prevent abuse and fraud, and enf…».
            'To keep the service secure, prevent abuse and fraud, and enforce the Terms and Conditions.',
            // Esta línea sirve para agregar el ítem: «To obtain internal, aggregated usage statistics (for example…».
            'To obtain internal, aggregated usage statistics (for example, how many people use the app each day and from which platform) to operate and improve the service. These are calculated from our own records, without third-party tools.',
          ],
        },
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «Legal basis: processing is based on your prior, express and informed a…».
          text: 'Legal basis: processing is based on your prior, express and informed authorization (in particular for health and fitness data, which are sensitive data), on providing the service you request when accepting the Terms and Conditions, and on the need to keep the service secure, under Law 1581 of 2012 of {{jurisdiction}} and its implementing regulations.',
        },
      ],
    },
    {
      // Esta línea sirve para identificar la sección con el id "salud".
      id: 'salud',
      // Esta línea sirve para definir el título de la sección: «4. Health and fitness data».
      title: '4. Health and fitness data',
      // Esta línea sirve para abrir los bloques de contenido de la sección.
      blocks: [
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «Some data you log in {{brandName}} (weight, height, age, sex, body com…».
          text: 'Some data you log in {{brandName}} (weight, height, age, sex, body composition and measurements, sleep quality, energy, muscle soreness, diet and how you felt about your workouts in the weekly check-in) may be considered health-related or sensitive data under applicable law. That is why we ask for a specific, separate authorization to process it.',
        },
        {
          // Esta línea sirve para indicar que el bloque es una lista.
          type: 'list',
          // Esta línea sirve para abrir los ítems de la lista.
          items: [
            // Esta línea sirve para agregar el ítem: «We use it only to personalize your routines and nutrition ta…».
            'We use it only to personalize your routines and nutrition targets and to show your progress.',
            // Esta línea sirve para agregar el ítem: «We do not sell it or use it for advertising.…».
            'We do not sell it or use it for advertising.',
            // Esta línea sirve para agregar el ítem: «It is only visible to your trainer if you connect with one i…».
            'It is only visible to your trainer if you connect with one in the app, and to the {{brandName}} administration team when needed for support, moderation or security.',
            // Esta línea sirve para agregar el ítem: «It is optional to the extent that you may skip logging measu…».
            'It is optional to the extent that you may skip logging measurements, the pre-workout check or the nutrition section; without some of it (for example level, goals or weight) the app cannot generate a personalized routine.',
          ],
        },
        {
          // Esta línea sirve para indicar que el bloque es una nota destacada.
          type: 'note',
          // Esta línea sirve para incluir el texto: «{{brandName}} is a training and tracking tool. It does not provide med…».
          text: '{{brandName}} is a training and tracking tool. It does not provide medical services, does not diagnose, and does not replace advice from a doctor, dietitian or other health professional.',
        },
      ],
    },
    {
      // Esta línea sirve para identificar la sección con el id "destinatarios".
      id: 'destinatarios',
      // Esta línea sirve para definir el título de la sección: «5. Who we share your data with».
      title: '5. Who we share your data with',
      // Esta línea sirve para abrir los bloques de contenido de la sección.
      blocks: [
        // Esta línea sirve para incluir el párrafo: «We do not sell your data…».
        { type: 'p', text: 'We do not sell your data. It is only shared in these cases:' },
        {
          // Esta línea sirve para indicar que el bloque es una lista.
          type: 'list',
          // Esta línea sirve para abrir los ítems de la lista.
          items: [
            // Esta línea sirve para agregar el ítem: «Your trainer: if you connect with a trainer in {{brandName}}…».
            'Your trainer: if you connect with a trainer in {{brandName}}, they can see what they need to coach you (your name, routines, workouts and progress) and chat with you.',
            // Esta línea sirve para agregar el ítem: «Other users: your name and lifts appear in rankings only if …».
            'Other users: your name and lifts appear in rankings only if you turn on "Public rankings"; in challenges you join, your name and progress appear in the challenge leaderboard.',
            // Esta línea sirve para agregar el ítem: «{{brandName}} administration team: limited access to what is…».
            '{{brandName}} administration team: limited access to what is needed for support, moderation, record review and order management. Your support requests and weekly check-in answers are only seen by this team — not by your trainer or other users.',
            // Esta línea sirve para agregar el ítem: «Technical providers that provide services to {{brandName}} (…».
            'Technical providers that provide services to {{brandName}} (see section 6), only with the data each one needs.',
            // Esta línea sirve para agregar el ítem: «Shipping companies: when applicable, the carrier delivering …».
            'Shipping companies: when applicable, the carrier delivering your order receives the delivery name, phone and address.',
            // Esta línea sirve para agregar el ítem: «Authorities: when required by law or by an order of a compet…».
            'Authorities: when required by law or by an order of a competent authority.',
          ],
        },
      ],
    },
    {
      // Esta línea sirve para identificar la sección con el id "terceros".
      id: 'terceros',
      // Esta línea sirve para definir el título de la sección: «6. Third-party services».
      title: '6. Third-party services',
      // Esta línea sirve para abrir los bloques de contenido de la sección.
      blocks: [
        {
          // Esta línea sirve para indicar que el bloque es una tabla.
          type: 'table',
          // Esta línea sirve para definir los encabezados de la tabla.
          headers: ['Service', 'Purpose', 'Information it may receive'],
          // Esta línea sirve para abrir las filas de la tabla.
          rows: [
            [
              // Esta línea sirve para agregar la celda de la fila: «Google (Firebase Authentication and Google Sign-In…».
              'Google (Firebase Authentication and Google Sign-In)',
              // Esta línea sirve para agregar la celda de la fila: «Signing in or up with your Google account, only if…».
              'Signing in or up with your Google account, only if you choose that option.',
              // Esta línea sirve para agregar la celda de la fila: «The Google account data you authorize sharing (nam…».
              'The Google account data you authorize sharing (name, email, photo) and technical connection data. Google processes it under its own privacy policy.',
            ],
            // Esta línea sirve para agregar la fila de «Google Fonts (web only)».
            ['Google Fonts (web only)', 'Loading the interface typeface.', 'Your IP address and technical browser data when downloading the font.'],
            [
              // Esta línea sirve para agregar la celda de la fila: «Expo push notification service (mobile app)…».
              'Expo push notification service (mobile app)',
              // Esta línea sirve para agregar la celda de la fila: «Delivering push notifications to your phone, throu…».
              'Delivering push notifications to your phone, through Firebase Cloud Messaging (Google) or Apple Push Notification service.',
              // Esta línea sirve para agregar la celda de la fila: «Your device notification identifier and the notifi…».
              'Your device notification identifier and the notification content (for example, the sender name and the beginning of the message).',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Your browser push service (web)…».
              'Your browser push service (web)',
              // Esta línea sirve para agregar la celda de la fila: «Delivering browser notifications, if you enable th…».
              'Delivering browser notifications, if you enable them.',
              // Esta línea sirve para agregar la celda de la fila: «An encrypted notification; the provider depends on…».
              'An encrypted notification; the provider depends on your browser (for example Google, Mozilla or Apple).',
            ],
            [
              // Esta línea sirve para agregar la celda de la fila: «Open Food Facts…».
              'Open Food Facts',
              // Esta línea sirve para agregar la celda de la fila: «Looking up food nutrition information by name or b…».
              'Looking up food nutrition information by name or barcode.',
              // Esta línea sirve para agregar la celda de la fila: «Only the search text or barcode. The request is ma…».
              'Only the search text or barcode. The request is made by the {{brandName}} server, without data that identifies you.',
            ],
            // Esta línea sirve para agregar la fila de «{{emailProvider}}».
            ['{{emailProvider}}', 'Sending verification and password recovery emails.', 'Your email address and the message content.'],
            [
              // Esta línea sirve para agregar la celda de la fila: «ngrok and Cloudflare (connection tunnels)…».
              'ngrok and Cloudflare (connection tunnels)',
              // Esta línea sirve para agregar la celda de la fila: «Today the {{brandName}} server (database and files…».
              'Today the {{brandName}} server (database and files) runs on equipment owned by the controller, with no external hosting provider, and is connected to the Internet through these tunnels.',
              // Esta línea sirve para agregar la celda de la fila: «Traffic between the app and the server passes thro…».
              'Traffic between the app and the server passes through them, including the data you send and receive. If a hosting provider is hired, it will be disclosed in a new version of this policy.',
            ],
            // Esta línea sirve para agregar la fila de «WhatsApp (Meta)».
            ['WhatsApp (Meta)', 'Only if you choose to contact us via WhatsApp from the app.', 'The conversation happens in WhatsApp and is governed by its policies.'],
          ],
        },
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «Some of these providers may process data outside your country. When th…».
          text: 'Some of these providers may process data outside your country. When that happens, the safeguards required by the law applicable in {{jurisdiction}} will apply.',
        },
      ],
    },
    {
      // Esta línea sirve para identificar la sección con el id "conservacion".
      id: 'conservacion',
      // Esta línea sirve para definir el título de la sección: «7. How long we keep your data».
      title: '7. How long we keep your data',
      // Esta línea sirve para abrir los bloques de contenido de la sección.
      blocks: [
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «We keep your data while your account is active. If your account is del…».
          text: 'We keep your data while your account is active. If your account is deleted, the data linked to it (profile, workouts, measurements, nutrition, messages, notifications and consents) is deleted too, unless the law requires keeping it longer. The internal audit log of administrative actions may keep references to the account for security reasons. Specific periods: {{retentionPeriod}}.',
        },
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «We keep a record of which version of each legal document you accepted …».
          text: 'We keep a record of which version of each legal document you accepted and when, as proof of your consent, for as long as your account exists.',
        },
      ],
    },
    {
      // Esta línea sirve para identificar la sección con el id "derechos".
      id: 'derechos',
      // Esta línea sirve para definir el título de la sección: «8. Your rights».
      title: '8. Your rights',
      // Esta línea sirve para abrir los bloques de contenido de la sección.
      blocks: [
        // Esta línea sirve para incluir el párrafo sobre la ley colombiana de protección de datos personales.
        { type: 'p', text: 'Under Colombian personal data protection law (Law 1581 of 2012 and its implementing regulations), you can:' },
        {
          // Esta línea sirve para indicar que el bloque es una lista.
          type: 'list',
          // Esta línea sirve para abrir los ítems de la lista.
          items: [
            // Esta línea sirve para agregar el ítem: «Find out what data about you we process and get a copy.…».
            'Find out what data about you we process and get a copy.',
            // Esta línea sirve para agregar el ítem: «Ask us to correct inaccurate or incomplete data. You can cor…».
            'Ask us to correct inaccurate or incomplete data. You can correct much of it yourself from the app settings.',
            // Esta línea sirve para agregar el ítem: «Delete your account and your data at any time from Settings …».
            'Delete your account and your data at any time from Settings > Delete my account, or ask us to delete specific data, where applicable.',
            // Esta línea sirve para agregar el ítem: «Withdraw your consent where processing is based on it. Withd…».
            'Withdraw your consent where processing is based on it. Withdrawal does not affect prior processing and may prevent us from continuing to provide features that depend on that data.',
            // Esta línea sirve para agregar el ítem: «Request information about how we use your data and about thi…».
            'Request information about how we use your data and about this policy.',
            // Esta línea sirve para agregar el ítem: «File a complaint with {{supervisoryAuthority}}, after first …».
            'File a complaint with {{supervisoryAuthority}}, after first submitting your query or claim to us.',
          ],
        },
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «To exercise any of these rights, write to {{privacyEmail}} from the em…».
          text: 'To exercise any of these rights, write to {{privacyEmail}} from the email linked to your account, stating your request. We may ask for additional information to verify your identity before handling it.',
        },
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «From the app settings you can also, at any time: turn your appearance …».
          text: 'From the app settings you can also, at any time: turn your appearance in public rankings on or off, turn push notifications on or off and, on the web, change your cookie preferences.',
        },
      ],
    },
    {
      // Esta línea sirve para identificar la sección con el id "seguridad".
      id: 'seguridad',
      // Esta línea sirve para definir el título de la sección: «9. Security».
      title: '9. Security',
      // Esta línea sirve para abrir los bloques de contenido de la sección.
      blocks: [
        {
          // Esta línea sirve para indicar que el bloque es una lista.
          type: 'list',
          // Esta línea sirve para abrir los ítems de la lista.
          items: [
            // Esta línea sirve para agregar el ítem: «Passwords are stored with a cryptographic hash, never in pla…».
            'Passwords are stored with a cryptographic hash, never in plain text.',
            // Esta línea sirve para agregar el ítem: «You can enable two-step verification; its secret is stored e…».
            'You can enable two-step verification; its secret is stored encrypted.',
            // Esta línea sirve para agregar el ítem: «Access to information is limited by role (user, trainer, adm…».
            'Access to information is limited by role (user, trainer, administration).',
            // Esta línea sirve para agregar el ítem: «Repeated sign-in and sign-up attempts are automatically rate…».
            'Repeated sign-in and sign-up attempts are automatically rate-limited.',
          ],
        },
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «No system is completely infallible. If we detect a security incident a…».
          text: 'No system is completely infallible. If we detect a security incident affecting your data, we will act as required by applicable law.',
        },
      ],
    },
    {
      // Esta línea sirve para identificar la sección con el id "menores".
      id: 'menores',
      // Esta línea sirve para definir el título de la sección: «10. Minors».
      title: '10. Minors',
      // Esta línea sirve para abrir los bloques de contenido de la sección.
      blocks: [
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «The app accepts users between 15 and 70 years old. To use {{brandName}…».
          text: 'The app accepts users between 15 and 70 years old. To use {{brandName}} without an adult\'s authorization you must be at least {{minimumAge}}. If you are younger, you need authorization from your parent or legal guardian.',
        },
      ],
    },
    {
      // Esta línea sirve para identificar la sección con el id "cookies".
      id: 'cookies',
      // Esta línea sirve para definir el título de la sección: «11. Cookies and local storage».
      title: '11. Cookies and local storage',
      // Esta línea sirve para abrir los bloques de contenido de la sección.
      blocks: [
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «The web version uses cookies and browser local storage. Details are in…».
          text: 'The web version uses cookies and browser local storage. Details are in the Cookie Policy. The mobile app keeps your session and some preferences in the phone\'s secure storage; it does not use tracking or advertising cookies.',
        },
      ],
    },
    {
      // Esta línea sirve para identificar la sección con el id "cambios".
      id: 'cambios',
      // Esta línea sirve para definir el título de la sección: «12. Changes to this policy».
      title: '12. Changes to this policy',
      // Esta línea sirve para abrir los bloques de contenido de la sección.
      blocks: [
        {
          // Esta línea sirve para indicar que el bloque es un párrafo.
          type: 'p',
          // Esta línea sirve para incluir el texto: «Each version of this policy has a number and a date. If we make import…».
          text: 'Each version of this policy has a number and a date. If we make important changes, we will ask you to review and accept the new version before you keep using the app.',
        },
      ],
    },
  ],
};
